### ISSUE TITLE
Investigate ArgoCD stuck state when deploying

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [Equal-Vote/argocd#6]
Reported by @ArendPeter 

Probably due to extreme austerity measures in the cluster. I thought we had disabled ArgoCD, because it takes too many resources...

**Comment by csamuele** [comment]
Error during file reading [Error: ENOENT: no such file or directory, open '/usr/src/app/packages/packages/frontend/build/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/src/app/packages/packages/frontend/build/index.html'
}
